### ISSUE TITLE
Niffler triggers highlighting even though it wasn't enabled when opened

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#30] opened 2015-09-02 10:53 UTC
I've looked at the source code and it seems that you set nohls when opening niffler and then restore it to whatever it was when closing it but for some reason I'm seeing a lot of highlighting after I've used for example NifflerTags even though it was not enabled when I started Niffler.

Not sure what to give you to make debugging easier if you're not seeing it :smile:

**Comment by pgdouyon** [comment] 2015-09-02 14:45
Was it disabled via `:set nohlsearch` or via `:nohlsearch`?  I can't reproduce if it was disabled with the former command, but I can reproduce if it was disabled using the latter command.

Unfortunately, Vim's treatment of `:nohlsearch` is completely insane and it provides no way of determining whether or not it's been used.  In this case, the options would be to not disable `hlsearch` in the Niffler window or to always leave highlighting off when leaving Niffler via `:nohlsearch`.

Another extremely hacky solution would be to clear the `Search` and `IncSearch` hl-groups upon entering Niffler, and then restoring them upon leaving instead of ever messing with `hlsearch`.  As ugly as it is, this is probably the best approach.

**Comment by marlun** [comment] 2015-09-03 07:13
It was disabled using `:nohlsearch`

```
nnoremap <silent> <c-l> :nohlsearch<CR>
```

Not sure about the solutions. What about adding a way for a user to run custom commands when Niffler closes leaving the option to the user? I guess you want to keep things like that to a minimum but it could be an option since `hlsearch` is a special case?

Maybe we should write to the vim-dev mailinglist (or open an issue on github) too about not being able to see if :nohlseach has been used?

**Comment by marlun** [comment] 2015-09-03 07:22
Have you seen the `v:hlsearch` variable? It seems like it could be used in this situation but maybe I'm missing something?

**Comment by pgdouyon** [comment] 2015-09-03 15:15
Ohhh wow yea that's perfect, I haven't come across that variable but that should definitely do it.  Not sure why I couldn't find it yesterday but we can combine that with `&hlsearch` to figure out what state the highlighting is currently in and call `:nohlsearch` if `&hlsearch == 1` and `v:hlsearch == 0`

**Comment by pgdouyon** [comment] 2015-09-03 16:14
Should be fixed now, thanks for helping track this down and finding the `v:hlsearch` variable!

**Comment by marlun** [comment] 2015-09-03 19:06
Great! Glad to help.

**Comment by marlun** [comment] 2015-10-12 07:07
Today I noticed that the highlighting bug seems to have reapeared. If I start vim, open :NifflerMRU and hit \* on a variable which appears multiple times they are not highlighted unless I run :hlsearch. 

I made a `git bisect` and it seems to be b57adb19a55f9b5c0da73663c08e65f9ce6cc27f which is the first "bad" commit.

Feels weird that I didn't notice this before though.

**Comment by marlun** [comment] 2015-10-12 07:08
Sorry I noticed now that this bug was for a different highlight problem, should I create a new issue with the problem above?

**Comment by pgdouyon** [comment] 2015-10-12 14:37
Ahh I'm an idiot, sorry about that.  Should be fixed now.

**Closed as completed** 2015-10-12 14:37 UTC

**Comment by marlun** [comment] 2015-10-13 07:03
Thanks, no worries :smile:
