### ISSUE TITLE
Getting errors on :Niffler %

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#15] opened 2015-04-15 11:53 UTC
When opening a file using `:Niffler .` I'm getting this from time to time:

``` vim
Error detected while processing function <SNR>27_niffler..<SNR>27_keypress_event_loop..<SNR>27_open_current_window..<SNR>27_open_selection..<SNR>27_quit_niffler:
line    4:
E474: Invalid argument
```

(open current window) and (open vertical split):

``` vim
Error detected while processing function <SNR>27_niffler..<SNR>27_keypress_event_loop..<SNR>27_open_vert_split..<SNR>27_open_selection..<SNR>27_quit_niffler:
line    4:
E474: Invalid argument
```

Realising this isn't much to go on I'm not sure how to get more information to give to you?

**Comment by pgdouyon** [comment] 2015-04-15 14:25
Yea I know about the problem and for the life of me I can't figure out what's causing it.  I'm wondering if it's not some kind of weird bug in vim/neovim.  The offending line is:

``` vim
call setmatches(b:niffler_save_matches)
```

Which just restores the highlighting (anything created with `matchadd()` or `:match`) that was cleared when creating the Niffler buffer.  `b:niffler_save_matches` is set with the line:

``` vim
let b:niffler_save_matches = getmatches() | call clearmatches()
```

so we should just be piping the output of `getmatches()` into `setmatches()` and there's no sane reason why this should ever fail.

Particularly the fact that it doesn't fail consistently reinforces my belief that it's a vim/neovim bug.  Probably a weird race condition or garbage collection bug.  If you ever find a way to make this reproducible please let me know, I've tried every combination I can think of and can't find a way to reliably produce the error.

Eventually, I'll probably just prepend that line with `silent!` to swallow the errors, but I'm not ready to give up on fixing this just yet.  Especially since user defined highlighting won't be restored when it fails.

I might also add some logging capabilities to that section to capture it on the few times it does happen.

**Comment by marlun** [comment] 2015-04-16 07:50
I'll try to take a look at it when I get the time too and I'll try to see if I can find a way to reliably reproduce it.

**Comment by marlun** [comment] 2015-04-18 11:48
OK I've made some investigation about this and I believe I've might have found the problem.

Make sure you've got **matchparen.vim** plugin enabled (which you pretty much have unless you've got `:let loaded_matchparen = 1` in your config) and when invoking `Niffler .` make sure the cursor is on a character which is highlighted because of matchparen.vim.

When that happens the matchparen plugin uses `matchaddpos()` instead of `matchadd()` to add matches and those can't be set with `setmatches()`.

From `:help matchaddpos()`:

``` vim
<       Matches added by |matchaddpos()| are returned by
        |getmatches()| with an entry "pos1", "pos2", etc., with the
        value a list like the {pos} item.
        These matches cannot be set via |setmatches()|, however they
        can still be deleted by |clearmatches()|.
```

Not sure about the best way to solve it without adding special handling for the matchparen.vim plugin which seems like something you'd like to avoid.

What is the reason you're not using `setlocal cursorline` instead of `\%#`? Couldn't that remove the need to do anything with **get/setmatches**?

**Comment by pgdouyon** [comment] 2015-04-18 20:05
Wow that's terrible, thank you so much for tracking this down though, that's a really nasty bug.  I get why Vim might not want to restore these match groups in some situations, but to handle it this way seems completely insane to me.

The reason I wanted to use a custom match group is because most colorschemes (rightly so) use a very subtle, low-contrast background color for the CursorLine group.  But I wanted Niffler's default status line to be more vibrant and easy to see, that was one thing I really liked about Unite.vim's cursor line (which also uses a custom match group).  

Unfortunately, highlight groups are global so I can't change it for just the Niffler window and if you open Niffler while having two windows open in a split and `cursorline` set in both windows, then the cursorline in the non-Niffler window will suddenly turn a very bright shade of purple and it's really awkward to see out of the corner of your eye.

I think the best way to handle this is to filter any position matches out of the `getmatches()` list and not even attempt to restore them.  

The reason being that any plugin that uses `matchaddpos()` already needs to listen to autocmds like `CursorMoved`, `BufEnter`, or `BufLeave` because highlighting defined for one buffer's line may not be appropriate when another buffer is switched into the same window.  These autocmds are still fired when entering/leaving the Niffler window so plugins should still be able to respond to them.

**Comment by marlun** [comment] 2015-04-18 20:24
I agree that the current line in Niffler should be vibrant and easy to see and it makes more sense to use a custom match group. Filter away! :smile: Glad I could help!

**Comment by pgdouyon** [comment] 2015-04-18 20:34
Interestingly enough, while testing the fix for this bug I noticed that Niffler's highlight group is cleared whenever the colorscheme is changed.  So I'll have to also push a fix that links Niffler to the Error highlight group instead of the purple color I had been using.  Doesn't pop quite as much but should make Niffler much more stable.

**Comment by pgdouyon** [comment] 2015-04-18 20:47
Should be fixed now, let me know if this error still pops up for you and thanks again for your help!

**Closed as completed** 2015-04-18 20:46 UTC
