### ISSUE TITLE
Using generated tag info in current buffer to go to the tag

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#17] opened 2015-04-19 16:34 UTC
Right now when using `NifflerTags %` you are able to see the tags in the current buffer, filter them but when you hit _ENTER_ it fails unless you've previously generated a tags file. Since the tags are generated on demand anyway (for current buffer) it would be great if one could use it without previously generating a tags file too.

**Comment by pgdouyon** [comment] 2015-04-27 17:41
Sorry haven't had a chance to get to this yet, it's been a busy week.  The fix for this should be pretty simple and I can push it out in the next couple of days. In the meantime though, I highly recommend the [Gutentags](https://github.com/ludovicchabant/vim-gutentags) plugin for managing tag files.

**Comment by marlun** [comment] 2015-04-28 08:44
No worries, I'll try Gutentags, only seen vim-easytags before and it has always seemed a little bloated. Features of Gutentags sounds great.

**Comment by marlun** [comment] 2015-05-15 06:55
After using Gutentags for some time now I have to say it's working really great. I've never had to think about genereting tha tags but it has always been working. :+1:

**Comment by pgdouyon** [comment] 2015-05-15 07:20
Yea it actually still makes me smile when I create a new function and then call NifflerTags % a few seconds later and it's already there ready to go.  It's definitely the best ctags solution I've come across.  

Although, I still want to close out this bug just for the sake of correctness of Niffler's interface so this issue will probably be my top priority this weekend :smile:

**Closed as completed** 2015-06-02 05:59 UTC

**Comment by pgdouyon** [comment] 2015-06-02 06:02
@marlun 

I pushed quite a few changes to the ctags integration, let me know what you think of them. 

 The biggest change is stabilizing things, adding a NifflerTselect command, and adding tag information to the Niffler window so that you can search not only by tag name, but also by filename or text surrounding the tag.  Also needed to add <C-A> and <C-E> mappings to enable scrolling long lines of text (which is hard to avoid when adding the tag information)

**Comment by pgdouyon** [comment] 2015-06-02 06:21
Also just a word of warning, when you update to the latest your MRU list will be wiped out if you were using it.  It's because I moved the Niffler logic to the autoload folder to speed up startup times and the MRU location moved with it.  If you want you can just recopy over the current one from vim-niffler/plugin to vim-niffler/autoload.

**Comment by marlun** [comment] 2015-06-02 09:07
Sounds great, will update and get back to you when I've used it some.

**Comment by marlun** [comment] 2015-06-02 09:14
How do you use `NifflerTselect` (or :tselect)? I'm having a hard time getting my head around it. I never use (and probably never have used) :tselect.

I usually just use `NifflerTags %` to go to a function in the file I'm currently in. When I want to go to another function I usually open the file first with `Niffler .` and then run `NifflerTags %` to go to the function. I'm having a feeling I could improve my workflow :smile:

**Comment by pgdouyon** [comment] 2015-06-02 15:20
`:tselect` and `NifflerTselect` are for navigating in a situation where you have multiple tags with the same name.  

In Java for example, this could be an interface method (something like getProtocol()) that's implemented in 5 other classes.  If you just used `<C-]>` on the name of the interface method, it's a bit of a tossup which implementation it takes you to.  In this case, you would use `:tselect` or `NifflerTselect` to see the different locations for that tag, and then with Niffler you can filter down by filename or surrounding text to get to the desired implementation.

Also, the performance of `NifflerTags`, to search through all the tags in the project, has been dramatically improved so it should be easier to just run `NifflerTags` and then type the tag name and then filename if you need to filter down further.  `NifflerTags` used to sort the tags output, which caused a massive performance hit (I have one file with 100,000 tags and it took about 30 seconds to sort it), but with the changes to the architecture I removed the sorting and it should be pretty peformant.  My idea for `NifflerTags` is to be kind of like IntelliJ's SearchEverywhere (not sure if you're familiar with that functionality).

**Comment by pgdouyon** [comment] 2015-06-03 06:32
Actually after playing with it today I really hate this change.  I think it's necessary but needs a lot of improvement.  

I find that including the tag information (which is the necessary part) adds a lot of noise to the list and makes it difficult to filter.  

I'm toying with the idea of special casing the filtering in the case of a tag search to only search for the tag name and completely ignore the extra context information.  I'll have to use it a bit more though to get a better feel for it.  Let me know if you have any ideas whenever you get a chance to try this change out.

**Comment by marlun** [comment] 2015-06-03 07:57
Not sure why but when I use `NifflerTags %` now, filter the list to a specific one and hit enter I'm taken to the bottom of the file (last line) instead of the correct position.

**Comment by pgdouyon** [comment] 2015-06-03 14:22
Hmm, that's really strange I can't reproduce at all.  Try making sure you're updated to the latest and restart vim?

**Comment by marlun** [comment] 2015-06-04 09:25
Seems to work for me at my home computer, will debug at work on monday.

I'm not sure about the usefulness of showing context next to the names, it looks very messy to me. Here's an example from a file:

```
sortArrayOnDate  ==>  /^function sortArrayOnDate($a, $b) {$/;"
sortArrayOnDescription  ==>  /^function sortArrayOnDescription($a, $b) {$/;"
sortArrayOnId  ==>  /^function sortArrayOnId($a, $b) {$/;"
sortArrayOnSubtotal  ==>  /^function sortArrayOnSubtotal($a, $b) {$/;"
sortArrayOnTax  ==>  /^function sortArrayOnTax($a, $b) {$/;"
sortArrayOnTotal  ==>  /^function sortArrayOnTotal($a, $b) {$/;"
sortArrayOnUserId  ==>  /^function sortArrayOnUserId($a, $b) {$/;"
sortItems  ==>  /^function sortItems($items, $orderby, $sortorder) {$/;"
```

It looks a lot messier but gives me no extra info.

**Comment by marlun** [comment] 2015-06-04 09:25
OK, it does give me the parameter list which is extra info.

**Comment by pgdouyon** [comment] 2015-06-04 15:55
Yea I definitely agree that it's very messy.  The main purpose is to handle the situation where you have mutliple tags in the same file with the same name.  Adding the info gives extra context so that you can choose the correct tag to jump to.

But the noise is almost overwhelming, one thing that could help though is adding syntax highlighting to help make the tagname standout.  Ideally we would also align the contextual information, but alignment is pretty difficult to implement.  I could also try to strip out some of the noise like the "/^" and "$/;" at the beginning and end.

**Comment by marlun** [comment] 2015-06-05 06:50
Would be nice too if all the extra characters was not added? `/^` and `$/;"`. If we could pick only the parameters that would be nice too but since it's different between many languages that seems like a lot of work. Showing only something like this would be nice :) 

```
sortItems($items, $orderby, $sortOrder)
sortItems($items, $orderby)
sortItems($items)
```

**Comment by pgdouyon** [comment] 2015-06-05 15:48
Agreed, what do you think about a separator string, right now it's using `==>`, but even that feels noisy to me, not sure if it needs more whitespace or if the separator should just be all whitespace (like 2 tab characters or something)

**Comment by marlun** [comment] 2015-06-06 10:14
I feel like it all depends on how clean you can get the second part. It probably feels noisy because the second part is so noisy. 

```
sortItems ==> /^function sortItems($items, $orderby, $sortorder) {$/;"
sortItems / /^function sortItems($items, $orderby, $sortorder) {$/;"
sortItems - /^function sortItems($items, $orderby, $sortorder) {$/;"
sortItems > /^function sortItems($items, $orderby, $sortorder) {$/;"
```

```
sortItems ==> sortItems($items, $orderby, $sortorder)
sortItems / sortItems($items, $orderby, $sortorder)
sortItems - sortItems($items, $orderby, $sortorder)
sortItems > sortItems($items, $orderby, $sortorder)
```

**Comment by marlun** [comment] 2015-06-09 09:14
Still having the same problem at work when using `NifflerTags %`. Not sure how to debug it. I've made sure I've got the latest version and I've removed and regenerated the tags file. It did work fine at home.

Looking at the tags file it doesn't seem to have any line numbers for the function I just happend to look at. The function I used for testing is called shippingForm and in the tags file all it has is the following:

```
shippingForm  /Users/marlun/Work/project/class/controllers/OrderController.php  /^  function shippingForm($request, $orderId, $identifier) {$/;"  f class:OrderController
```

I don't know how it's supposed to look but it feels to me that there should be some info about the location, how else do you know where to jump to?

**Comment by marlun** [comment] 2015-06-09 10:21
Not sure but it might have something to do with my ctags installation (installed https://github.com/fishman/ctags using brew on OSX)

**Comment by marlun** [comment] 2015-06-09 10:28
I removed it and installed the normal exuberant-ctags but still got the same result.

**Comment by marlun** [comment] 2015-06-09 11:06
If I go into the vim-niffler folder and open autoload/niffler.vim it works great so there might be something with PHP files. I've also noticed that it doesn't matter if the lines are in there or not. There are no numbers in the tags file for niffler.vim but it still works fine.

However it doesn't explain why it works at home.

**Comment by marlun** [comment] 2015-06-09 12:21
Sorry for all of the comments (mails) I've added some echom to debug but I'm at work so I can't put much time into it and honestly I don't understand it right now:

In open_tag I've added some echom statements:

```
function! s:open_tag(prompt, open_cmd)
    let selection = substitute(getline("."), '\s*$', '', '')
    let tag_excmd = map([selection], b:niffler_parse_tag_excmd)[0]
    let tag_filename = map([selection], b:niffler_parse_tag_filename)[0]
    let open_cmd = bufexists(tag_filename) ? "buffer" : a:open_cmd
    echom selection
    echom b:niffler_parse_tag_excmd
    echom b:niffler_parse_tag_filename
    echom open_cmd
    call s:close_niffler()
    normal! m'
    execute "silent keepjumps keeppatterns" open_cmd "+".escape(tag_excmd, ' \') fnameescape(tag_filename)
endfunction
```

Which resulted in this output:

```
shippingForm  ==>  /^
matchstr(split(v:val, "\\V".s:tag_delimiter)[1], ".*\\$\\ze")
'/Users/marlun/Work/project/class/controllers/OrderController.php'
buffer
```

Seeing anything that looks wrong?

**Comment by pgdouyon** [comment] 2015-06-09 13:49
No worries about all of the emails, thanks for taking so much time to look into this.

The brew version of ctags is fine, Niffler uses the pattern in the ctags file to find the line to jump to, so it doesn't need line numbers.  When you select a tag for Niffler essentially it runs: 
`edit +/<PATTERN> <FILENAME>`
The `+` argument to `edit` lets you pass an excmd which will be run upon opening the file, in this case that excmd is a search for the ctags pattern which would let it jump directly to it.

As for the echom output that first line looks very wrong.  The selection should look something like:
`shippingForm  ==>  /^  function shippingForm($request, $orderId, $identifier) {$/;"`
Which is just the line that was selected when you pressed enter.

By any chance is the whitespace preceding the shippingForm function definition a tab character?  If it is then that would definitely explain it.  The `cut` command splits the ctags line at tab characters and passes that to Niffler, but if the function definition has a tab character then `cut` would split it at the tab character (which is in between `/^` and `function shippingForm`) instead of grabbing the whole pattern.

I'm working on a big overhaul of the tags functionality again to try and clean up these noise problems, should be done in a day or two.  For now though since it's clearly so broken I would recommend just going into the vim-niffler folder in your Vim runtime directory and reset to the previous version:
`git reset --hard 431002c`

**Comment by marlun** [comment] 2015-06-10 08:15
Yes, I use TAB characters for indentation :smile: I'll go back to last version until the update then.

Update: After changing back it works great again.

**Comment by pgdouyon** [comment] 2015-06-18 09:05
@marlun: pushed a big change to the tags functionality that should hopefully have cleaned up the interface and also removed the bugs that were present earlier.  

let me know if you find any bugs with it, it was a pretty massive overhaul so I wouldn't be shocked if some things slipped through the cracks.

**Comment by marlun** [comment] 2015-06-20 21:35
Seems to work great and it looks a lot better. :+1:  Haven't used it that much yet though.
