### ISSUE TITLE
Broken on latest neovim

### ISSUE THREAD

**Issue by marlun** [pgdouyon/vim-niffler#49] opened 2019-09-20 04:52 UTC
Niffler seems to be broken on latest neovim giving a lot of messages like this when you start to filter:

    || niffler#niffler[12]
    || <SNR>63_keypress_event_loop[4]
    || E5677: Error writing input to shell-command: EPIPE

Guessing there's something fundamental that's been changed and they want you to do something in another way.

**Comment by pgdouyon** [comment] 2019-09-23 19:37
Hmm that's unfortunate, I don't have the latest neovim installed yet to test it out. I'll try and investigate a bit to see what changes need to be made.

**Comment by pgdouyon** [comment] 2019-09-23 19:40
It actually looks like I've encountered a similar error 3 years ago and reported it on the Neovim issue tracker: https://github.com/neovim/neovim/issues/5791

I would assume there was a similar API change made

**Comment by marlun** [comment] 2019-09-24 05:54
Yes, I also found that it only happens when the Niffler buffer was full of entries. Tried to debug it some more and found that it seems to happen the second time getchar() is called inside s:keypress_event_loop, which felt weird to me.

**Comment by marlun** [comment] 2019-09-30 08:50
Now it only seem to happen with the `NifflerMRU` command. `Niffler` seems to work fine.

Update: Unless I write something and remove it to so the prompt is empty, then I get the error.

**Comment by pgdouyon** [comment] 2019-09-30 10:53
Bizarre, it looks like the latest version of Neovim still isn't available on Homebrew so I'll probably have to manually build it to test this out.

**Comment by marlun** [comment] 2019-10-08 09:00
Can't you just add --HEAD? :)

**Comment by marlun** [comment] 2019-10-23 07:40
Now I'm not using --HEAD anymore since 0.4.2 is released in homebrew but it has the same problem.

**Comment by pgdouyon** [comment] 2020-10-12 20:01
Unable to reproduce on neovim 0.4.4 (current latest stable release), closing for now

**Closed as completed** 2020-10-13 16:53 UTC

**Comment by pgdouyon** [comment] 2020-10-13 16:56
I was finally able to reproduce the error today although I still have no idea what causes it. It seems to only be thrown when the input list is very large, when I originally tested by looking for all files in a relatively small repository there was no error thrown. It was only when I tried using Niffler in a very large repository that I saw the error.

The error was being thrown by the `getchar()` function but this seems like some kind of bug in Neovim because the function was still able to return the input character and there didn't seem to be anything wrong with calling it. I silenced the error for now to at least prevent it from breaking Niffler. Will have to follow up with the Neovim team for more information.

Should be fixed now. Closing.
